[DEFAULT]
# Indirizzo IP e porta TCP/IP del Keithley 2461
dev-address = 192.168.100.10
dev-port = 5025

# Cartelle di input (profili CSV) e output (risultati delle misure)
in-dir = .
out-dir = ./output

# Intervallo di campionamento in secondi
sampling-time = 0.5

# Limiti massimi di sicurezza hardware/software (compliance)
voltage-compliance = 7.0
current-compliance = 5.0